# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kural\Desktop\pymysql\manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manager(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(170, 70, 631, 531))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border:none;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 611, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 130, 241, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(100, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(208, 210, 241, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(90, 210, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(90, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.button7 = QtWidgets.QPushButton(self.tab)
        self.button7.setGeometry(QtCore.QRect(250, 370, 111, 31))
        self.button7.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.button7.setObjectName("button7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 290, 241, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(230, 420, 241, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 641, 511))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(70, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button4 = QtWidgets.QPushButton(self.tab_4)
        self.button4.setGeometry(QtCore.QRect(250, 280, 111, 31))
        self.button4.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.button4.setObjectName("button4")
        self.comboBox_ct1 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_ct1.setGeometry(QtCore.QRect(430, 160, 141, 31))
        self.comboBox_ct1.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_ct1.setObjectName("comboBox_ct1")
        self.comboBox_p1 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_p1.setGeometry(QtCore.QRect(130, 160, 141, 31))
        self.comboBox_p1.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_p1.setObjectName("comboBox_p1")
        self.comboBox_c1 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_c1.setGeometry(QtCore.QRect(280, 160, 141, 31))
        self.comboBox_c1.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_c1.setObjectName("comboBox_c1")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 330, 601, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(70, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.button5 = QtWidgets.QPushButton(self.tab_5)
        self.button5.setGeometry(QtCore.QRect(250, 280, 111, 31))
        self.button5.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.button5.setObjectName("button5")
        self.comboBox_p2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_p2.setGeometry(QtCore.QRect(130, 160, 141, 31))
        self.comboBox_p2.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_p2.setObjectName("comboBox_p2")
        self.comboBox_c2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_c2.setGeometry(QtCore.QRect(280, 160, 141, 31))
        self.comboBox_c2.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_c2.setObjectName("comboBox_c2")
        self.comboBox_ct2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_ct2.setGeometry(QtCore.QRect(432, 160, 141, 31))
        self.comboBox_ct2.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox_ct2.setObjectName("comboBox_ct2")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 340, 601, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(140, 120, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(290, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(150, 210, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(290, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.button6 = QtWidgets.QPushButton(self.tab_3)
        self.button6.setGeometry(QtCore.QRect(260, 300, 111, 31))
        self.button6.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.button6.setObjectName("button6")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(190, 350, 291, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_3, "")
        self.button1 = QtWidgets.QPushButton(Form)
        self.button1.setGeometry(QtCore.QRect(20, 160, 121, 41))
        self.button1.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(Form)
        self.button2.setGeometry(QtCore.QRect(20, 220, 121, 41))
        self.button2.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(Form)
        self.button3.setGeometry(QtCore.QRect(20, 280, 121, 41))
        self.button3.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.button3.setObjectName("button3")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 811, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "修改学生的健康码，若该学生暂没有健康码，会自动生成"))
        self.label_9.setText(_translate("Form", "学号"))
        self.comboBox_2.setItemText(0, _translate("Form", "健康"))
        self.comboBox_2.setItemText(1, _translate("Form", "存疑"))
        self.comboBox_2.setItemText(2, _translate("Form", "患病"))
        self.label_10.setText(_translate("Form", "健康状态"))
        self.label_11.setText(_translate("Form", "备注信息"))
        self.button7.setText(_translate("Form", "提交"))
        self.label_12.setText(_translate("Form", "请输入信息后点击提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.label_3.setText(_translate("Form", "地区"))
        self.button4.setText(_translate("Form", "提交"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "            添加风险地区            "))
        self.label_4.setText(_translate("Form", "地区"))
        self.button5.setText(_translate("Form", "提交"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "            移除风险地区           "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.label.setText(_translate("Form", "检测管编号"))
        self.label_2.setText(_translate("Form", "检测结果"))
        self.comboBox.setItemText(0, _translate("Form", "阴性"))
        self.comboBox.setItemText(1, _translate("Form", "阳性"))
        self.button6.setText(_translate("Form", "提交"))
        self.label_5.setText(_translate("Form", "请输入数据后点击提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Tab 3"))
        self.button1.setText(_translate("Form", "健康码处理"))
        self.button2.setText(_translate("Form", "风险地区调整"))
        self.button3.setText(_translate("Form", "核酸结果上传"))
