# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Py\Desktop\vscode\pymysql\student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_stu(object):
    def setupUi(self, MainWindow_stu):
        MainWindow_stu.setObjectName("MainWindow_stu")
        MainWindow_stu.resize(800, 600)
        MainWindow_stu.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow_stu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(190, 10, 601, 581))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border:none;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 20, 601, 541))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.comboBox_tem = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_tem.setGeometry(QtCore.QRect(180, 70, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_tem.setFont(font)
        self.comboBox_tem.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_tem.setObjectName("comboBox_tem")
        self.comboBox_tem.addItem("")
        self.comboBox_tem.addItem("")
        self.comboBox_tem.addItem("")
        self.comboBox_tem.addItem("")
        self.comboBox_county = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_county.setGeometry(QtCore.QRect(390, 180, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_county.setFont(font)
        self.comboBox_county.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_county.setObjectName("comboBox_county")
        self.comboBox_county.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit.setGeometry(QtCore.QRect(10, 290, 551, 91))
        self.textEdit.setStyleSheet("border: 2px solid #f3f3f3;\n"
"border-color:rgb(77, 123, 255);\n"
"font: 10pt \"微软雅黑\";\n"
"border-radius:10px;\n"
"background-color: rgb(237, 242, 255);")
        self.textEdit.setObjectName("textEdit")
        self.get_report = QtWidgets.QPushButton(self.tab_7)
        self.get_report.setGeometry(QtCore.QRect(190, 400, 191, 41))
        self.get_report.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.get_report.setObjectName("get_report")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 591, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(0, 240, 591, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox_province = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_province.setGeometry(QtCore.QRect(0, 180, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_province.setFont(font)
        self.comboBox_province.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_province.setObjectName("comboBox_province")
        self.comboBox_province.addItem("")
        self.comboBox_city = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_city.setGeometry(QtCore.QRect(180, 180, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_city.setFont(font)
        self.comboBox_city.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_city.setObjectName("comboBox_city")
        self.comboBox_city.addItem("")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(0, 20, 591, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_report_1 = QtWidgets.QLabel(self.tab_7)
        self.label_report_1.setGeometry(QtCore.QRect(131, 450, 301, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_report_1.setFont(font)
        self.label_report_1.setStyleSheet("color:rgb(255, 0, 0);")
        self.label_report_1.setText("")
        self.label_report_1.setObjectName("label_report_1")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.get_report_2 = QtWidgets.QPushButton(self.tab_8)
        self.get_report_2.setGeometry(QtCore.QRect(190, 400, 191, 41))
        self.get_report_2.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.get_report_2.setObjectName("get_report_2")
        self.tableWidget_report = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_report.setGeometry(QtCore.QRect(5, 51, 571, 311))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.tableWidget_report.setFont(font)
        self.tableWidget_report.setStyleSheet("/********QTableWidget*********/\n"
"QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
"    \n"
"              font-size: 19px;                /*11榜*/\n"
"          border: 1px solid rgb(255, 255, 255);\n"
"       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
"        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
"          min-height:40px;\n"
"           \n"
"} \n"
" \n"
" \n"
"QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding-left: 2px;\n"
"        min-width:60px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
"QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgb(255, 255, 255,180);\n"
"        padding-top: 3px;\n"
"        min-width:60px;\n"
"        \n"
"}\n"
"QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
" \n"
" \n"
"QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;                         /*设置右内边距*/\n"
"        image: url(:/arrow_up.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"     \n"
"}\n"
"QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;\n"
"        image: url(:/arrow_down.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"     \n"
"}\n"
"QTableWidget,QTableView {\n"
"                font-size: 17px;                /*10榜*/                \n"
"                color : rgb(1,37,116);                \n"
"        border: 2px solid rgb(100, 188, 238);        \n"
"        background: rgb(248,248,248);\n"
"        gridline-color: rgb(196,226,255);    \n"
"        text-align: center;    \n"
"        outline:0px;            /*禁止焦点*/\n"
"        \n"
"}\n"
"QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none; \n"
"        background: rgba(251,251,253,200);\n"
"       \n"
"       /* border-right: 1px solid rgb(100, 188, 238); */\n"
"        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
"}\n"
"QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
"        background: rgba(207,230,253,200);\n"
"        color : rgb(1,37,116);                \n"
"}\n"
" \n"
" \n"
"QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
"{ \n"
"    background: rgb(250,250,250); \n"
"}\n"
" \n"
"QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
"{ \n"
"    background: rgb(240,247,254); \n"
"}")
        self.tableWidget_report.setAutoScroll(True)
        self.tableWidget_report.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_report.setObjectName("tableWidget_report")
        self.tableWidget_report.setColumnCount(3)
        self.tableWidget_report.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(2, item)
        self.tableWidget_report.horizontalHeader().setDefaultSectionSize(123)
        self.tableWidget_report.verticalHeader().setDefaultSectionSize(37)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(2, 10, 591, 531))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_5)
        self.dateTimeEdit.setGeometry(QtCore.QRect(170, 80, 211, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
" QDateTimeEdit::up-button{\n"
"subcontrol-origin:border;\n"
"     subcontrol-position:right;\n"
"      60px;\n"
"     height: 60px;                \n"
" }\n"
" QDateTimeEdit::down-button{subcontrol-origin:border;\n"
"     subcontrol-position:left;\n"
"      60px;\n"
"     height: 60px;\n"
" }")
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 501, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 501, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_leave = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_leave.setGeometry(QtCore.QRect(170, 190, 141, 41))
        self.lineEdit_leave.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/")
        self.lineEdit_leave.setObjectName("lineEdit_leave")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 501, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.comboBox_province_2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_province_2.setGeometry(QtCore.QRect(0, 300, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_province_2.setFont(font)
        self.comboBox_province_2.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_province_2.setObjectName("comboBox_province_2")
        self.comboBox_province_2.addItem("")
        self.comboBox_city_2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_city_2.setGeometry(QtCore.QRect(180, 300, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_city_2.setFont(font)
        self.comboBox_city_2.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_city_2.setObjectName("comboBox_city_2")
        self.comboBox_city_2.addItem("")
        self.comboBox_county_2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_county_2.setGeometry(QtCore.QRect(390, 300, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_county_2.setFont(font)
        self.comboBox_county_2.setStyleSheet("/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"    /*min-height: 5em;*/\n"
"\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"")
        self.comboBox_county_2.setObjectName("comboBox_county_2")
        self.comboBox_county_2.addItem("")
        self.get_leave = QtWidgets.QPushButton(self.tab_5)
        self.get_leave.setGeometry(QtCore.QRect(180, 370, 201, 41))
        self.get_leave.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.get_leave.setObjectName("get_leave")
        self.label_leave_1 = QtWidgets.QLabel(self.tab_5)
        self.label_leave_1.setGeometry(QtCore.QRect(160, 420, 241, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_leave_1.setFont(font)
        self.label_leave_1.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_leave_1.setText("")
        self.label_leave_1.setObjectName("label_leave_1")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(320, 190, 71, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_leave = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_leave.setGeometry(QtCore.QRect(0, 40, 571, 311))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.tableWidget_leave.setFont(font)
        self.tableWidget_leave.setStyleSheet("/********QTableWidget*********/\n"
"QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
"    \n"
"              font-size: 15px;                /*11榜*/\n"
"          border: 1px solid rgb(255, 255, 255);\n"
"       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
"        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
"          min-height:40px;\n"
"           \n"
"} \n"
" \n"
" \n"
"QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding-left: 2px;\n"
"        min-width:60px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
"QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgb(255, 255, 255,180);\n"
"        padding-top: 3px;\n"
"        min-width:60px;\n"
"        \n"
"}\n"
"QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
" \n"
" \n"
"QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;                         /*设置右内边距*/\n"
"        image: url(:/arrow_up.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"     \n"
"}\n"
"QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;\n"
"        image: url(:/arrow_down.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"     \n"
"}\n"
"QTableWidget,QTableView {\n"
"                font-size: 15px;                /*10榜*/                \n"
"                color : rgb(1,37,116);                \n"
"        border: 2px solid rgb(100, 188, 238);        \n"
"        background: rgb(248,248,248);\n"
"        gridline-color: rgb(196,226,255);    \n"
"        text-align: center;    \n"
"        outline:0px;            /*禁止焦点*/\n"
"        \n"
"}\n"
"QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none; \n"
"        background: rgba(251,251,253,200);\n"
"       \n"
"       /* border-right: 1px solid rgb(100, 188, 238); */\n"
"        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
"}\n"
"QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
"        background: rgba(207,230,253,200);\n"
"        color : rgb(1,37,116);                \n"
"}\n"
" \n"
" \n"
"QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
"{ \n"
"    background: rgb(250,250,250); \n"
"}\n"
" \n"
"QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
"{ \n"
"    background: rgb(240,247,254); \n"
"}")
        self.tableWidget_leave.setAutoScroll(True)
        self.tableWidget_leave.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_leave.setObjectName("tableWidget_leave")
        self.tableWidget_leave.setColumnCount(4)
        self.tableWidget_leave.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_leave.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_leave.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_leave.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_leave.setHorizontalHeaderItem(3, item)
        self.tableWidget_leave.horizontalHeader().setDefaultSectionSize(123)
        self.tableWidget_leave.verticalHeader().setDefaultSectionSize(37)
        self.get_leave_2 = QtWidgets.QPushButton(self.tab_6)
        self.get_leave_2.setGeometry(QtCore.QRect(180, 380, 201, 41))
        self.get_leave_2.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.get_leave_2.setObjectName("get_leave_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.image = QtWidgets.QLabel(self.tab_3)
        self.image.setGeometry(QtCore.QRect(140, 120, 280, 280))
        self.image.setText("")
        self.image.setObjectName("image")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(30, 40, 501, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(130, 215, 255);\n"
" border-radius: 10px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.health_show_button = QtWidgets.QPushButton(self.tab_3)
        self.health_show_button.setGeometry(QtCore.QRect(210, 440, 141, 41))
        self.health_show_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.health_show_button.setObjectName("health_show_button")
        self.label_8.raise_()
        self.health_show_button.raise_()
        self.image.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_test = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_test.setGeometry(QtCore.QRect(10, 80, 571, 311))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.tableWidget_test.setFont(font)
        self.tableWidget_test.setStyleSheet("/********QTableWidget*********/\n"
"QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
"    \n"
"              font-size: 15px;                /*11榜*/\n"
"          border: 1px solid rgb(255, 255, 255);\n"
"       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
"        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
"          min-height:40px;\n"
"           \n"
"} \n"
" \n"
" \n"
"QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding-left: 2px;\n"
"        min-width:60px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
"QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgb(255, 255, 255,180);\n"
"        padding-top: 3px;\n"
"        min-width:60px;\n"
"        \n"
"}\n"
"QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
" \n"
" \n"
"QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;                         /*设置右内边距*/\n"
"        image: url(:/arrow_up.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"     \n"
"}\n"
"QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;\n"
"        image: url(:/arrow_down.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"     \n"
"}\n"
"QTableWidget,QTableView {\n"
"                font-size: 15px;                /*10榜*/                \n"
"                color : rgb(1,37,116);                \n"
"        border: 2px solid rgb(100, 188, 238);        \n"
"        background: rgb(248,248,248);\n"
"        gridline-color: rgb(196,226,255);    \n"
"        text-align: center;    \n"
"        outline:0px;            /*禁止焦点*/\n"
"        \n"
"}\n"
"QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none; \n"
"        background: rgba(251,251,253,200);\n"
"       \n"
"       /* border-right: 1px solid rgb(100, 188, 238); */\n"
"        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
"}\n"
"QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
"        background: rgba(207,230,253,200);\n"
"        color : rgb(1,37,116);                \n"
"}\n"
" \n"
" \n"
"QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
"{ \n"
"    background: rgb(250,250,250); \n"
"}\n"
" \n"
"QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
"{ \n"
"    background: rgb(240,247,254); \n"
"}")
        self.tableWidget_test.setAutoScroll(True)
        self.tableWidget_test.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_test.setObjectName("tableWidget_test")
        self.tableWidget_test.setColumnCount(4)
        self.tableWidget_test.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_test.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_test.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_test.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_test.setHorizontalHeaderItem(3, item)
        self.tableWidget_test.horizontalHeader().setDefaultSectionSize(123)
        self.tableWidget_test.verticalHeader().setDefaultSectionSize(37)
        self.tube_button_2 = QtWidgets.QPushButton(self.tab_4)
        self.tube_button_2.setGeometry(QtCore.QRect(140, 420, 261, 51))
        self.tube_button_2.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tube_button_2.setObjectName("tube_button_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.password_lineEdit_new = QtWidgets.QLineEdit(self.tab_9)
        self.password_lineEdit_new.setGeometry(QtCore.QRect(160, 190, 221, 41))
        self.password_lineEdit_new.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"font: 10pt \"微软雅黑\";\n"
"border-radius:10px\n"
"")
        self.password_lineEdit_new.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit_new.setObjectName("password_lineEdit_new")
        self.password_comfirm_lineEdit = QtWidgets.QLineEdit(self.tab_9)
        self.password_comfirm_lineEdit.setGeometry(QtCore.QRect(160, 260, 221, 41))
        self.password_comfirm_lineEdit.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"font: 10pt \"微软雅黑\";\n"
"border-radius:10px\n"
"")
        self.password_comfirm_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_comfirm_lineEdit.setObjectName("password_comfirm_lineEdit")
        self.password_lineEdit_old = QtWidgets.QLineEdit(self.tab_9)
        self.password_lineEdit_old.setGeometry(QtCore.QRect(160, 120, 221, 41))
        self.password_lineEdit_old.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"font: 10pt \"微软雅黑\";\n"
"border-radius:10px\n"
"")
        self.password_lineEdit_old.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit_old.setObjectName("password_lineEdit_old")
        self.leave_button_2 = QtWidgets.QPushButton(self.tab_9)
        self.leave_button_2.setGeometry(QtCore.QRect(200, 330, 141, 41))
        self.leave_button_2.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.leave_button_2.setObjectName("leave_button_2")
        self.label_9 = QtWidgets.QLabel(self.tab_9)
        self.label_9.setGeometry(QtCore.QRect(180, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.report_button = QtWidgets.QPushButton(self.centralwidget)
        self.report_button.setGeometry(QtCore.QRect(20, 150, 141, 41))
        self.report_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.report_button.setObjectName("report_button")
        self.leave_button = QtWidgets.QPushButton(self.centralwidget)
        self.leave_button.setGeometry(QtCore.QRect(20, 220, 141, 41))
        self.leave_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.leave_button.setObjectName("leave_button")
        self.tube_button = QtWidgets.QPushButton(self.centralwidget)
        self.tube_button.setGeometry(QtCore.QRect(20, 360, 141, 41))
        self.tube_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tube_button.setObjectName("tube_button")
        self.health_button = QtWidgets.QPushButton(self.centralwidget)
        self.health_button.setGeometry(QtCore.QRect(20, 290, 141, 41))
        self.health_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.health_button.setObjectName("health_button")
        self.change_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_password_button.setGeometry(QtCore.QRect(20, 430, 141, 41))
        self.change_password_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.change_password_button.setObjectName("change_password_button")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 10, 441, 31))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        MainWindow_stu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_stu)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_stu)

    def retranslateUi(self, MainWindow_stu):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_stu.setWindowTitle(_translate("MainWindow_stu", "学生管理"))
        self.comboBox_tem.setItemText(0, _translate("MainWindow_stu", "37.3℃以下"))
        self.comboBox_tem.setItemText(1, _translate("MainWindow_stu", "37.3℃~37.8℃"))
        self.comboBox_tem.setItemText(2, _translate("MainWindow_stu", "37.8℃~39.0℃"))
        self.comboBox_tem.setItemText(3, _translate("MainWindow_stu", "39.0℃以上"))
        self.comboBox_county.setItemText(0, _translate("MainWindow_stu", "--请选择区/县"))
        self.textEdit.setMarkdown(_translate("MainWindow_stu", "若当前无明显症状填写无即可\n"
"\n"
""))
        self.textEdit.setHtml(_translate("MainWindow_stu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">若当前无明显症状填写无即可</p></body></html>"))
        self.get_report.setText(_translate("MainWindow_stu", "提交今日填报"))
        self.label_2.setText(_translate("MainWindow_stu", "当日位置  "))
        self.label_3.setText(_translate("MainWindow_stu", "当前症状  "))
        self.comboBox_province.setItemText(0, _translate("MainWindow_stu", "--请选择省"))
        self.comboBox_city.setItemText(0, _translate("MainWindow_stu", "--请选择市"))
        self.label.setText(_translate("MainWindow_stu", "当日体温  "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow_stu", "              今日填报             "))
        self.get_report_2.setText(_translate("MainWindow_stu", "显示近7日填报"))
        item = self.tableWidget_report.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_stu", "填报日期"))
        item = self.tableWidget_report.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_stu", "当日体温"))
        item = self.tableWidget_report.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_stu", "填报地点"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow_stu", "              我的历史填报            "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_stu", "Tab 1"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow_stu", "yyyy-M-d H:mm"))
        self.label_5.setText(_translate("MainWindow_stu", "离校时间"))
        self.label_6.setText(_translate("MainWindow_stu", "请假时长"))
        self.label_7.setText(_translate("MainWindow_stu", "请假去向"))
        self.comboBox_province_2.setItemText(0, _translate("MainWindow_stu", "--请选择省"))
        self.comboBox_city_2.setItemText(0, _translate("MainWindow_stu", "--请选择市"))
        self.comboBox_county_2.setItemText(0, _translate("MainWindow_stu", "--请选择区/县"))
        self.get_leave.setText(_translate("MainWindow_stu", "提交请假申请"))
        self.label_4.setText(_translate("MainWindow_stu", "天"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow_stu", "              请假申请              "))
        item = self.tableWidget_leave.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_stu", "离校时间"))
        item = self.tableWidget_leave.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_stu", "请假时长"))
        item = self.tableWidget_leave.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_stu", "请假去向"))
        item = self.tableWidget_leave.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_stu", "是否通过"))
        self.get_leave_2.setText(_translate("MainWindow_stu", "查看请假申请"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow_stu", "            我的历史申请            "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_stu", "Tab 2"))
        self.label_8.setText(_translate("MainWindow_stu", "我的健康码"))
        self.health_show_button.setText(_translate("MainWindow_stu", "查看"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow_stu", "Tab 3"))
        item = self.tableWidget_test.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_stu", "检测时间"))
        item = self.tableWidget_test.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_stu", "检测员号"))
        item = self.tableWidget_test.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_stu", "试管编号"))
        item = self.tableWidget_test.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_stu", "检测结果"))
        self.tube_button_2.setText(_translate("MainWindow_stu", "查看14天内核酸结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow_stu", "Tab 4"))
        self.password_lineEdit_new.setPlaceholderText(_translate("MainWindow_stu", "新密码"))
        self.password_comfirm_lineEdit.setPlaceholderText(_translate("MainWindow_stu", "确认新密码"))
        self.password_lineEdit_old.setPlaceholderText(_translate("MainWindow_stu", "请输入旧密码以确认身份"))
        self.leave_button_2.setText(_translate("MainWindow_stu", "确认修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow_stu", "Tab 5"))
        self.report_button.setText(_translate("MainWindow_stu", "疫情填报"))
        self.leave_button.setText(_translate("MainWindow_stu", "请假管理"))
        self.tube_button.setText(_translate("MainWindow_stu", "查看核酸结果"))
        self.health_button.setText(_translate("MainWindow_stu", "查看健康码"))
        self.change_password_button.setText(_translate("MainWindow_stu", "修改密码"))
