# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Py\Desktop\vscode\pymysql\teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_tea(object):
    def setupUi(self, MainWindow_tea):
        MainWindow_tea.setObjectName("MainWindow_tea")
        MainWindow_tea.resize(800, 600)
        MainWindow_tea.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow_tea)
        self.centralwidget.setObjectName("centralwidget")
        self.report_button = QtWidgets.QPushButton(self.centralwidget)
        self.report_button.setGeometry(QtCore.QRect(10, 220, 171, 41))
        self.report_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.report_button.setObjectName("report_button")
        self.leave_button = QtWidgets.QPushButton(self.centralwidget)
        self.leave_button.setGeometry(QtCore.QRect(10, 290, 171, 41))
        self.leave_button.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.leave_button.setObjectName("leave_button")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(200, 30, 581, 531))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border:none;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_report = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_report.setGeometry(QtCore.QRect(10, 80, 571, 311))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.tableWidget_report.setFont(font)
        self.tableWidget_report.setStyleSheet("/********QTableWidget*********/\n"
"QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
"    \n"
"              font-size: 15px;                /*11榜*/\n"
"          border: 1px solid rgb(255, 255, 255);\n"
"       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
"        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
"          min-height:40px;\n"
"           \n"
"} \n"
" \n"
" \n"
"QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding-left: 2px;\n"
"        min-width:60px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
"QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
"        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
"          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgb(255, 255, 255,180);\n"
"        padding-top: 3px;\n"
"        min-width:60px;\n"
"        \n"
"}\n"
"QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
"        color: white;                            /*字体白色*/\n"
"        background: rgb(11,82,202);                /*背景深蓝色*/\n"
"}\n"
"QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
"        color: white;\n"
"        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
"}\n"
" \n"
" \n"
"QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;                         /*设置右内边距*/\n"
"        image: url(:/arrow_up.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"     \n"
"}\n"
"QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 10px;\n"
"        image: url(:/arrow_down.png);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"     \n"
"}\n"
"QTableWidget,QTableView {\n"
"                font-size: 15px;                /*10榜*/                \n"
"                color : rgb(1,37,116);                \n"
"        border: 2px solid rgb(100, 188, 238);        \n"
"        background: rgb(248,248,248);\n"
"        gridline-color: rgb(196,226,255);    \n"
"        text-align: center;    \n"
"        outline:0px;            /*禁止焦点*/\n"
"        \n"
"}\n"
"QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none; \n"
"        background: rgba(251,251,253,200);\n"
"       \n"
"       /* border-right: 1px solid rgb(100, 188, 238); */\n"
"        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
"}\n"
"QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
"        background: rgba(207,230,253,200);\n"
"        color : rgb(1,37,116);                \n"
"}\n"
" \n"
" \n"
"QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
"{ \n"
"    background: rgb(250,250,250); \n"
"}\n"
" \n"
"QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
"{ \n"
"    background: rgb(240,247,254); \n"
"}")
        self.tableWidget_report.setAutoScroll(True)
        self.tableWidget_report.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_report.setObjectName("tableWidget_report")
        self.tableWidget_report.setColumnCount(4)
        self.tableWidget_report.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_report.setHorizontalHeaderItem(3, item)
        self.tableWidget_report.horizontalHeader().setDefaultSectionSize(123)
        self.tableWidget_report.verticalHeader().setDefaultSectionSize(37)
        self.dateEdit = QtWidgets.QDateEdit(self.tab)
        self.dateEdit.setGeometry(QtCore.QRect(220, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: rgb(237, 242, 255);/*背景颜色*/\n"
"    border-radius: 10px;/*圆角*/\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:rgb(77, 123, 255);/*边框颜色*/\n"
"\n"
"    padding-left: 10px;/*左侧边距*/\n"
" QDateEdit::up-button{\n"
"subcontrol-origin:border;\n"
"     subcontrol-position:right;\n"
"      60px;\n"
"     height: 60px;                \n"
" }\n"
" QDateEdit::down-button{subcontrol-origin:border;\n"
"     subcontrol-position:left;\n"
"      60px;\n"
"     height: 60px;\n"
" }")
        self.dateEdit.setDate(QtCore.QDate(2022, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(100, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 85, 255);")
        self.label.setObjectName("label")
        self.get_report = QtWidgets.QPushButton(self.tab)
        self.get_report.setGeometry(QtCore.QRect(190, 420, 191, 41))
        self.get_report.setStyleSheet("QPushButton{\n"
"    font: 12pt \"微软雅黑\";\n"
"    \n"
"    background-color:rgb(46, 154, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(46, 154, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color:rgb(46, 154, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.get_report.setObjectName("get_report")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow_tea.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_tea)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_tea)

    def retranslateUi(self, MainWindow_tea):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_tea.setWindowTitle(_translate("MainWindow_tea", "班主任管理"))
        self.report_button.setText(_translate("MainWindow_tea", "学生填报管理"))
        self.leave_button.setText(_translate("MainWindow_tea", "学生请假管理"))
        item = self.tableWidget_report.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_tea", "姓名"))
        item = self.tableWidget_report.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_tea", "学号"))
        item = self.tableWidget_report.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_tea", "当日体温"))
        item = self.tableWidget_report.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_tea", "填报地点"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow_tea", "yyyy-M-d"))
        self.label.setText(_translate("MainWindow_tea", "请选择日期"))
        self.get_report.setText(_translate("MainWindow_tea", "显示近7日填报"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_tea", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_tea", "Tab 2"))
